### ISSUE TITLE
withFontLoading can call setState on unmounted components

### ISSUE THREAD

**Issue by rolyatmax** [fusionjs/fusion-plugin-font-loader-react#142]
### Type of issue

Bug

### Description

It appears that the `withFontLoading` HOC calls `this.setState` once a font loads, [here](https://github.com/fusionjs/fusion-plugin-font-loader-react/blob/master/src/with-font-loading.js#L53-L56). In the case that the component unmounts before the font loads, however, React throws some warnings for calling `setState` on an unmounted component. According to [a React blog post](https://reactjs.org/blog/2015/12/16/ismounted-antipattern.html), we should probably make the promise returned by the `font-loader` module cancellable and cancel it in `componentWillUnmount`.

**Comment by angus-c** [comment]
Although the article says "isMounted is an Antipattern" here it seems exactly what we want. The article assumes the setState is for global state, in this case it's purely for local state so there is no risk of a memory leak that I can see.

Because `isMounted` is deprecated I'll just set local `this.mounted` props. It's a lot more efficient than bringing in all that `cancelPromise` code.
